apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-service
  description: My internal service
  tags:
    - internal
spec:
  type: service
  lifecycle: production
  owner: user:default/guest
